### PR TITLE
Added the Email verification functionality

### PR DESCRIPTION
**Pull request by Adittya-Gupta**
Here are the pictures 
WhatsApp Image 2022-12-06 at 2 30 14 PM
WhatsApp Image 2022-12-06 at 2 30 15 PM
WhatsApp Image 2022-12-06 at 2 30 15 PM (1)
Solved issue #3

### CODE REVIEW

**Comment by Adittya-Gupta** [comment]
@Sparsh752

**Comment by Sparsh752** [comment]
@Adittya-Gupta You have changed 392 files? Please commit only those files in which changes matter.

**Comment by Adittya-Gupta** [comment]
@Sparsh752 There are so many changes because of there are changes in UI and these changes are automatic if I do not commit these changes then the app will not function properly

**Comment by Adittya-Gupta** [comment]
But if you want I will commit only those files in which I made changes 😸

**Pull request closed without merging**
